<a href="https://colab.research.google.com/github/sourovw/data-science/blob/main/1-Python-Basics/2-numpy-basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([5, 8, 9])

In [3]:
a[0]

5

In [4]:
a = np.array([5, 8, 9, 4, 1])

In [5]:
len(a)

5

In [6]:
a[:]

array([5, 8, 9, 4, 1])

In [7]:
a[-3]

9

In [8]:
type(a)

numpy.ndarray

In [9]:
a.dtype

dtype('int64')

In [10]:
a.itemsize

8

In [11]:
a.ndim

1

In [12]:
a = np.array([[2, 5], [1, 7], [2, 6]])

In [13]:
a.ndim

2

In [14]:
a.itemsize

8

In [15]:
a.dtype

dtype('int64')

In [16]:
a

array([[2, 5],
       [1, 7],
       [2, 6]])

In [17]:
a.size

6

In [18]:
a.shape

(3, 2)

In [19]:
a = np.array([[2, 5], [1, 7], [2, 6], [9, 4]])

In [20]:
a.size

8

In [21]:
a = np.array([[2, 5], [1, 7], [2, 6], [9, 4]], dtype=float)

In [22]:
a.dtype

dtype('float64')

In [23]:
a.itemsize

8

In [24]:
a

array([[2., 5.],
       [1., 7.],
       [2., 6.],
       [9., 4.]])

In [25]:
a = np.array([[2, 5], [1, 7], [2, 6]], dtype=complex)

In [26]:
a

array([[2.+0.j, 5.+0.j],
       [1.+0.j, 7.+0.j],
       [2.+0.j, 6.+0.j]])

In [27]:
import numpy as np

In [28]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
np.ones((5, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [30]:
l = range(5)

In [31]:
l

range(0, 5)

In [32]:
np.arange(1, 6)

array([1, 2, 3, 4, 5])

In [33]:
np.arange(1, 5, 1)

array([1, 2, 3, 4])

In [34]:
np.arange(1, 11, 3)

array([ 1,  4,  7, 10])

In [35]:
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [36]:
np.linspace(1, 5, 5)

array([1., 2., 3., 4., 5.])

In [37]:
np.linspace(1, 5, 20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [38]:
import numpy as np

In [39]:
a = np.array([[1, 2], [3, 4], [5, 6]])

In [40]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
a.shape

(3, 2)

In [42]:
a.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
a = np.array([[3, 1], [5, 7], [0, 2]])

In [44]:
a.shape

(3, 2)

In [45]:
a.reshape(2, 3)

array([[3, 1, 5],
       [7, 0, 2]])

In [46]:
a.reshape(6, 1)

array([[3],
       [1],
       [5],
       [7],
       [0],
       [2]])

In [47]:
a.ravel()

array([3, 1, 5, 7, 0, 2])

In [48]:
a = a.ravel()

In [49]:
a

array([3, 1, 5, 7, 0, 2])

In [50]:
a = np.array([[1, 2], [3, 4], [5, 6]])

In [51]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [52]:
a.min()

1

In [53]:
a.max()

6

In [54]:
a.sum()

21

In [55]:
a.sum(axis=0)

array([ 9, 12])

In [56]:
a.sum(axis=1)

array([ 3,  7, 11])

In [57]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [58]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [59]:
np.std(a)

1.707825127659933

In [60]:
import numpy as np

In [61]:
a = np.array([[1, 2], [3, 4]])

In [62]:
b = np.array([[5, 6], [7, 8]])

In [63]:
a

array([[1, 2],
       [3, 4]])

In [64]:
b

array([[5, 6],
       [7, 8]])

In [65]:
a + b

array([[ 6,  8],
       [10, 12]])

In [66]:
a * b

array([[ 5, 12],
       [21, 32]])

In [67]:
a / b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [68]:
a

array([[1, 2],
       [3, 4]])

In [69]:
a.dot(b) # matrix

array([[19, 22],
       [43, 50]])

In [70]:
a

array([[1, 2],
       [3, 4]])

In [71]:
a.ravel() # linear

array([1, 2, 3, 4])